[package]
name = "diavasi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Diavasi server and administration executable"
readme = "../../README.md"

[[bin]]
name = "diavasi"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
diavasi = { workspace = true, default-features = false }
diavasi-adapter-mongodb = { workspace = true }
diavasi-adapter-postgres = { workspace = true }
diavasi-adapter-redis = { workspace = true }
diavasi-adapter-scylla = { workspace = true }
futures.workspace = true
mongodb = "3"
ratatui = "0.29"
redis = { version = "0.29", features = ["tokio-comp", "connection-manager"] }
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["full", "process"] }
reqwest = { workspace = true, features = ["blocking", "json", "rustls-tls"], default-features = false }
